/**
 * IPC channel name constants.
 *
 * All channels crossing the preload boundary are enumerated here.
 * Renderer never calls electron or node builtins directly.
 */
export const IPC = {
  // renderer → main (invoke)
  GET_APP_INFO: 'openpi:get-app-info',
  PICK_WORKSPACE: 'openpi:pick-workspace',
  SESSION_PROMPT: 'openpi:session-prompt',
  SESSION_STEER: 'openpi:session-steer',
  SESSION_FOLLOW_UP: 'openpi:session-follow-up',
  SESSION_BASH: 'openpi:session-bash',
  SESSION_ABORT: 'openpi:session-abort',
  GET_MODELS: 'openpi:get-models',
  SET_MODEL: 'openpi:set-model',
  SET_THINKING: 'openpi:set-thinking',
  GET_SESSION_STATS: 'openpi:get-session-stats',
  GET_WORKSPACES: 'openpi:get-workspaces',
  GET_SESSIONS: 'openpi:get-sessions',
  GET_SESSION_MESSAGES: 'openpi:get-session-messages',
  OPEN_SESSION: 'openpi:open-session',
  NEW_SESSION: 'openpi:new-session',
  GET_GIT_BRANCH: 'openpi:get-git-branch',
  GET_WORKSPACE_SUMMARY: 'openpi:get-workspace-summary',
  SET_WORKSPACE_TRUST: 'openpi:set-workspace-trust',
  WORKBENCH_CONTEXT_UPDATE: 'openpi:workbench-context-update',
  WORKBENCH_CONTEXT_GET: 'openpi:workbench-context-get',
  CHECK_PATH_PROTECTION: 'openpi:check-path-protection',
  GET_DIAGNOSTICS_BUNDLE: 'openpi:get-diagnostics-bundle',
  GET_CUSTOMIZATIONS: 'openpi:get-customizations',
  INSTALL_PACKAGE: 'openpi:install-package',
  REMOVE_PACKAGE: 'openpi:remove-package',
  SET_SESSION_NAME: 'openpi:set-session-name',
  FORK_SESSION: 'openpi:fork-session',
  GET_SESSION_TREE: 'openpi:get-session-tree',

  // PTY terminal (renderer → main)
  PTY_CREATE: 'openpi:pty-create',
  PTY_WRITE: 'openpi:pty-write',
  PTY_RESIZE: 'openpi:pty-resize',
  PTY_CLOSE: 'openpi:pty-close',

  // Preferences
  GET_PREF: 'openpi:get-pref',
  SET_PREF: 'openpi:set-pref',
  PLAY_SOUND_EFFECT: 'openpi:play-sound-effect',
  CHECK_PI_UPDATE: 'openpi:check-pi-update',
  INSTALL_PI_UPDATE: 'openpi:install-pi-update',

  // App self-update (renderer → main / main → renderer)
  APP_UPDATE_CHECK: 'openpi:app-update-check',
  APP_UPDATE_OPEN_RELEASE: 'openpi:app-update-open-release',
  APP_UPDATE_INSTALL: 'openpi:app-update-install',
  APP_UPDATE_STATUS: 'openpi:app-update-status',
  GET_CHANGELOG: 'openpi:get-changelog',

  // Git source control (renderer → main)
  GIT_STATUS: 'openpi:git-status',
  GIT_DIFF: 'openpi:git-diff',
  GIT_STAGE: 'openpi:git-stage',
  GIT_UNSTAGE: 'openpi:git-unstage',
  GIT_COMMIT: 'openpi:git-commit',
  GIT_DISCARD: 'openpi:git-discard',
  GIT_SYNC: 'openpi:git-sync',
  GIT_REFS: 'openpi:git-refs',
  GIT_CHECKOUT_BRANCH: 'openpi:git-checkout-branch',
  GIT_CREATE_BRANCH: 'openpi:git-create-branch',
  GIT_STASH_APPLY: 'openpi:git-stash-apply',
  GIT_STASH_POP: 'openpi:git-stash-pop',
  GIT_STASH_DROP: 'openpi:git-stash-drop',
  GIT_HISTORY: 'openpi:git-history',
  GIT_COMMIT_DIFF: 'openpi:git-commit-diff',
  GIT_REMOTE_URL: 'openpi:git-remote-url',
  GIT_FILE_TREE: 'openpi:git-file-tree',
  GIT_PANEL_MOUNTED: 'openpi:git-panel-mounted',
  GIT_GENERATE_COMMIT_MSG: 'openpi:git-generate-commit-msg',

  // main → renderer
  AGENT_CHANGED_FILES: 'openpi:agent-changed-files',
  READ_FILE: 'openpi:read-file',
  WRITE_FILE: 'openpi:write-file',
  DELETE_FILE: 'openpi:delete-file',
  FORMAT_FILE: 'openpi:format-file',
  SET_EXTENSION_ENABLED: 'openpi:set-extension-enabled',
  GET_FIRST_RUN: 'openpi:get-first-run',
  SEARCH_FILE_CONTENTS: 'openpi:search-file-contents',
  LIST_PROMPT_TEMPLATES: 'openpi:list-prompt-templates',
  FFF_FILE_SEARCH: 'openpi:fff-file-search',
  FFF_GREP: 'openpi:fff-grep',

  // Settings
  GET_SETTINGS: 'openpi:get-settings',
  SAVE_SETTINGS: 'openpi:save-settings',
  OPEN_EXTERNAL: 'openpi:open-external',
  READ_THEME_COLORS: 'openpi:read-theme-colors',
  READ_THEME_TOKENS: 'openpi:read-theme-tokens',
  ARCHIVE_SESSIONS: 'openpi:archive-sessions',
  LIST_ARCHIVED_SESSIONS: 'openpi:list-archived-sessions',
  UNARCHIVE_SESSIONS: 'openpi:unarchive-sessions',
  DELETE_SESSIONS: 'openpi:delete-sessions',
  LIST_SKILLS: 'openpi:list-skills',
  READ_SKILL_FILE: 'openpi:read-skill-file',
  LIST_DIRECTORY: 'openpi:list-directory',

  GET_PROVIDERS: 'openpi:get-providers',
  SET_PROVIDER_KEY: 'openpi:set-provider-key',
  REMOVE_PROVIDER_KEY: 'openpi:remove-provider-key',
  LOGIN_PROVIDER: 'openpi:login-provider',
  LOGOUT_PROVIDER: 'openpi:logout-provider',
  PROVIDER_LOGIN_EVENT: 'openpi:provider-login-event',
  RESOLVE_PROVIDER_PROMPT: 'openpi:resolve-provider-prompt',
  GET_CUSTOM_PROVIDERS: 'openpi:get-custom-providers',
  ADD_CUSTOM_PROVIDER: 'openpi:add-custom-provider',
  REMOVE_CUSTOM_PROVIDER: 'openpi:remove-custom-provider',

  // main → renderer (on)
  SESSION_EVENT: 'openpi:session-event',
  SESSION_READY: 'openpi:session-ready',
  SESSION_ERROR: 'openpi:session-error',
  SESSION_INDEX_UPDATED: 'openpi:session-index-updated',
  SEND_PROMPT: 'openpi:send-prompt',
  PTY_DATA: 'openpi:pty-data',
  PTY_EXIT: 'openpi:pty-exit',
  OUTPUT_APPEND: 'openpi:output-append',
  GET_OUTPUT_BUFFER: 'openpi:get-output-buffer',
  GIT_STATUS_CHANGED: 'openpi:git-status-changed',
  FILE_TREE_CHANGED: 'openpi:file-tree-changed',
  REMOTE_SESSION_STATUS: 'openpi:remote-session-status',
  REMOTE_SESSION_UPDATE: 'openpi:remote-session-update',
  GOAL_UPDATE: 'openpi:goal-update',
  PLAN_UPDATE: 'openpi:plan-update',
  ARTIFACT_UPDATE: 'openpi:artifact-update',
} as const
